repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    hooks:
    -   id: isort

-   repo: https://github.com/psf/black
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/mirrors-flake8
    hooks:
    -   id: flake8